local_costmap:
  global_frame: map #odom
  robot_base_frame: base_link
  update_frequency: 9 #50   #5.0 from ???
  publish_frequency: 2 #2
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05 #0.05
  transform_tolerance: .2000
